spring.application.name = med_cards
spring.datasource.url = jdbc:postgresql://localhost:5432/med_cards
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
#    create db
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
#spring.jpa.hibernate.ddl-auto = update
#    create db migrations
spring.datasource.hikari.schema=med_cards
spring.jpa.hibernate.ddl-auto = update

#    Multipart File Configuration
spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB

#    create db migrations
flyway.baselineOnMigrate=true
spring.flyway.schemas=med_cards
spring.flyway.locations=classpath:db/med_cards

#    settings swagger
springdoc.pathsToMatch=/disease/**, /patient/**, /dictionary/**

#spring.docker.compose.profiles.active=dev


