spring.datasource.url=jdbc:postgresql://localhost:5432/med_cards
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

#    Multipart File Configuration
spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB

#    settings swagger
springdoc.pathsToMatch=/disease/**, /patient/**, /dictionary/**

#spring.docker.compose.profiles.active=dev


